---
- hosts: localhost
  gather_facts: no
  #strategy: free

  vars_files:
    - colorschemes.yml

  vars:
    become: false
    colorscheme: "{{ colorscheme_tao_yang }}"
    ci: "{{ lookup('env', 'CI') | bool }}" # are we running in Travis?
    username: "{% if ci %}travis{% else %}siddharthist{% endif %}"
    home: "{% if ci  %}{{ playbook_dir }}{% else %}{{ lookup('env', 'HOME') }}{% endif %}"
    xdg_config_home: "{% if ci %}{{ playbook_dir }}{% else %}{{ lookup('env', 'XDG_CONFIG_HOME') }}{% endif %}"
    symlinks:
      # - src: aspell-dict
      #   dst: "{{ home }}/.aspell.en.pws"
      - src: beets.yml
        dst: "{{ xdg_config_home }}/beets/config.yaml"
      # - src: gtkrc-2.0
      #   dst: "{{ home }}/.gtkrc-2.0"
      #- src: gtkrc-3.0.ini
        #dst: "{{ xdg_config_home }}/gtk-3.0/settings.ini"
      - src: conkyrc
        dst: "{{ xdg_config_home }}/conky/conkyrc"
      - src: compton.conf
        dst: "{{ xdg_config_home }}/compton.conf"
      - src: gitconfig
        dst: "{{ home }}/.gitconfig"
      - src: gitignore
        dst: "{{ xdg_config_home }}/gitignore"
      - src: i3
        dst: "{{ xdg_config_home }}/i3/config"
      - src: library.blb
        dst: "{{ xdg_config_home }}/beets/library.blb"
      - src: latexmkrc
        dst: "{{ home }}/.latexmkrc"
      - src: latex-mode-snippets
        dst: "{{ home }}/.emacs.d/private/snippets/latex-mode"
        mode: "0775"
      - src: mutt/muttrc
        dst: "{{ home }}/.mutt/muttrc"
      - src: mutt/muttrc.zenburn
        dst: "{{ home }}/.mutt/muttrc.zenburn"
      - src: mutt/mailcap
        dst: "{{ home }}/.mutt/mailcap"
      - src: mutt/signature
        dst: "{{ home }}/.mutt/signature"
      - src: mutt/offlineimap.py
        dst: "{{ home }}/.mutt/offlineimap.py"
        mode: "0775"
      - src: offlineimaprc
        dst: "{{ home }}/.offlineimaprc"
      - src: pre-commit
        dst: "{{ home }}/.config/git/hooks/pre-commit"
      # Currently breaks GNOME on Fedora
      # - src: profile
      #   dst: "{{ home }}/.profile"
      #   mode: "0775"
      - src: ranger/commands.py
        dst: "{{ xdg_config_home }}/ranger/commands.py"
      - src: ranger/rc.conf
        dst: "{{ xdg_config_home }}/ranger/rc.conf"
      - src: ranger/scope.sh
        dst: "{{ xdg_config_home }}/ranger/scope.sh"
        mode: "0775"
      - src: spacemacs
        dst: "{{ home }}/.spacemacs"
      - src: spacemacs.desktop
        dst: "{{ home }}/.local/share/applications/spacemacs.desktop"
      - src: sxhkdrc
        dst: "{{ xdg_config_home }}/sxhkd/sxhkdrc"
      - src: urlview
        dst: "{{ home }}/.urlview"
      - src: xmodmap
        dst: "{{ home }}/.xmodmap"

  tasks:
    - name: configure nixos
      become: yes
      register: nixos
      file:
        follow: true
        state: link
        src: "{{ playbook_dir }}/nixos"
        path: /etc/nixos
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0660"
      when: "{{ (become | bool) and (not ci) }}"

    - name: make user symlink dirs
      file:
        follow: true
        state: directory
        path: "{{ item.dst | dirname }}"
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0775') }}"
      with_items: "{{ symlinks }}"

    - name: make user symlinks
      file:
        follow: true
        state: link
        src: "{{ playbook_dir }}/files/{{ item.src }}"
        path: "{{ item.dst }}"
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0664') }}"
      with_items: "{{ symlinks }}"

    - name: render user templates
      template:
        src: "{{ playbook_dir }}/templates/{{ item.src }}.j2"
        dest: "{{ item.dst }}"
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0664') }}"
      with_items:
        - src: Xresources
          dst: "{{ home }}/.Xresources"

    - name: handle xrdb changes
      command: xrdb -merge $HOME/.Xresources
      when: "{{ not ci }}"

    - name: create blank background
      command: convert -size 3200x1800 xc:#F6F6F6 ~/.config/wallpaper-blank.png

    - name: get nix logo
      get_url:
        url: https://raw.githubusercontent.com/NixOS/nixos-artwork/511e15e58471907c090d685f1bc7fc241260cc36/logo/nix-snowflake.svg
        dest: "{{ playbook_dir }}/files/nix-snowflake.svg"
        mode: 0660

    - name: convert nix logo to png
      command: >-
        inkscape -z -e ~/code/dots/files/nix-snowflake.png
        -w 1024 -h 1024
        ~/code/dots/files/nix-snowflake.svg

    # I manually edit this to create nix-snowflake-black
    - name: make transparent nix logo
      command: >-
        convert ~/code/dots/files/nix-snowflake.png
        -alpha set -channel RGBA -fill none -opaque white
        ~/code/dots/files/nix-snowflake-transparent.png

    - name: overlay nix logo
      command: >-
        convert ~/.config/wallpaper-blank.png
        ~/code/dots/files/nix-snowflake-black.png
        -gravity center -composite -background transparent -quality 100
        ~/.config/wallpaper.png

    - name: set new background
      command: feh --bg-scale ~/.config/wallpaper.png
