---
- hosts: localhost
  gather_facts: no
  #strategy: free

  vars_files:
    - colorschemes.yml

  vars:
    # username: "{% if ci %}travis{% else %}siddharthist{% endif %}"
    become: false
    minimal: false
    graphical: "{{ (true and not minimal) }}"
    colorscheme: "{{ colorscheme_tao_yang }}"
    ci: "{{ lookup('env', 'CI') | bool }}" # are we running in Travis?
    home: "{% if ci  %}{{ playbook_dir }}{% else %}{{ lookup('env', 'HOME') }}{% endif %}"
    xdg_config_home: "{% if ci %}{{ playbook_dir }}{% else %}{{ lookup('env', 'XDG_CONFIG_HOME') }}{% endif %}"
    # Per-host configuration
    dpi: 92
    cursor_size: 32
    urxvt_font_size: 6
    wallpaper: sarah-dorweiler-105888-unsplash.jpg

    symlinks:
      # - src: aspell-dict
      #   dst: "{{ home }}/.aspell.en.pws"
      - src: agignore
        dst: "{{ home }}/.agignore"
      - src: alacritty.yml
        dst: "{{ xdg_config_home }}/alacritty/alacritty.yml"
        graphical: true
      - src: beets.yml
        dst: "{{ xdg_config_home }}/beets/config.yaml"
      # - src: gtkrc-2.0
      #   dst: "{{ home }}/.gtkrc-2.0"
      #- src: gtkrc-3.0.ini
        #dst: "{{ xdg_config_home }}/gtk-3.0/settings.ini"
      - src: compton.conf
        dst: "{{ xdg_config_home }}/compton.conf"
        graphical: true
      - src: config.nix
        dst: "{{ xdg_config_home }}/nixpkgs/config.nix"
        minimal: true
      # status: can't figure out how to customize
      - src: gdbinit
        dst: "{{ home }}/.gdbinit"
        minimal: true
      - src: gdbinit.d
        dst: "{{ home }}/.gdbinit.d"
        minimal: true
      - src: git/gitconfig
        dst: "{{ home }}/.gitconfig"
      - src: git/galois.gitconfig
        dst: "{{ xdg_config_home }}/git/galois.gitconfig"
      - src: git/gitignore
        dst: "{{ xdg_config_home }}/git/gitignore"
      - src: git/pre-commit
        dst: "{{ home }}/.config/git/hooks/pre-commit"
      - src: home.nix
        dst: "{{ xdg_config_home }}/nixpkgs/home.nix"
        minimal: true
      - src: i3
        dst: "{{ xdg_config_home }}/i3/config"
        graphical: true
      - src: i3status.conf
        dst: "{{ xdg_config_home }}/i3status/config"
        graphical: true
      - src: keynavrc
        dst: "{{ xdg_config_home }}/keynav/keynavrc"
        graphical: true
      - src: library.blb
        dst: "{{ xdg_config_home }}/beets/library.blb"
      - src: latexmkrc
        dst: "{{ home }}/.latexmkrc"
      - src: matterhorn.ini
        dst: "{{ xdg_config_home }}/matterhorn/config.ini"
      - src: monitor/at-desk.sh
        dst: "{{ xdg_config_home }}/i3/scripts/at-desk.sh"
        mode: "0750"
        graphical: true
      - src: monitor/not-at-desk.sh
        dst: "{{ xdg_config_home }}/i3/scripts/not-at-desk.sh"
        mode: "0750"
        graphical: true
      - src: mutt
        dst: "{{ home }}/.mutt"
        mode: "0750"
      - src: my-cheatsheet.el
        dst: "{{ home }}/.emacs.d/private/local/my-cheatsheet.el"
      - src: eshell-aliases
        dst: "{{ home }}/.emacs.d/eshell/alias"
      - src: offlineimaprc
        dst: "{{ home }}/.offlineimaprc"
      - src: pet/config.toml
        dst: "{{ xdg_config_home }}/pet/config.toml"
      - src: pet/snippet.toml
        dst: "{{ xdg_config_home }}/pet/snippet.toml"
      # Currently breaks GNOME on Fedora
      # - src: profile
      #   dst: "{{ home }}/.profile"
      #   mode: "0775"
      - src: qutebrowser/config.py
        dst: "{{ xdg_config_home }}/qutebrowser/config.py"
        graphical: true
      - src: qutebrowser/config.yaml
        dst: "{{ xdg_config_home }}/qutebrowser/config.yaml"
        graphical: true
      - src: qutebrowser/quickmarks
        dst: "{{ xdg_config_home }}/qutebrowser/quickmarks"
        graphical: true
      - src: ranger/commands.py
        dst: "{{ xdg_config_home }}/ranger/commands.py"
        minimal: true
      - src: ranger/rc.conf
        dst: "{{ xdg_config_home }}/ranger/rc.conf"
        minimal: true
      - src: ranger/scope.sh
        dst: "{{ xdg_config_home }}/ranger/scope.sh"
        mode: "0750"
        minimal: true
      - src: rofi.rasi
        dst: "{{ xdg_config_home }}/rofi/config.rasi"
        graphical: true
      - src: snippets/java
        dst: "{{ home }}/.emacs.d/private/snippets/java-mode"
        mode: "0750"
      - src: snippets/haskell
        dst: "{{ home }}/.emacs.d/private/snippets/haskell-mode"
        mode: "0750"
      - src: snippets/latex
        dst: "{{ home }}/.emacs.d/private/snippets/latex-mode"
        mode: "0750"
      - src: snippets/nix
        dst: "{{ home }}/.emacs.d/private/snippets/nix-mode"
        mode: "0750"
      - src: snippets/org
        dst: "{{ home }}/.emacs.d/private/snippets/org-mode"
        mode: "0750"
      - src: snippets/sh
        dst: "{{ home }}/.emacs.d/private/snippets/sh-mode"
        mode: "0750"
      - src: snippets/saw-script
        dst: "{{ home }}/.emacs.d/private/snippets/saw-script-mode"
        mode: "0750"
      - src: spacemacs
        dst: "{{ home }}/.spacemacs"
      - src: spacemacs.desktop
        dst: "{{ home }}/.local/share/applications/spacemacs.desktop"
        graphical: true
      - src: ssh
        dst: "{{ home }}/.ssh/config"
      - src: sway
        dst: "{{ xdg_config_home }}/sway/config"
        graphical: true
      - src: sxhkdrc
        dst: "{{ xdg_config_home }}/sxhkd/sxhkdrc"
        graphical: true
      - src: tmux.conf
        dst: "{{ home }}/.tmux.conf"
      - src: "unsplash/{{ wallpaper }}"
        dst: "{{ xdg_config_home }}/wallpaper.jpg"
        graphical: true
      - src: urlview
        dst: "{{ home }}/.urlview"
      - src: xmodmap
        dst: "{{ home }}/.xmodmap"
        graphical: true
      # - src: Xresources
      #   dst: "{{ home }}/.Xresources"
      - src: zsh.d
        dst: "{{ home }}/.zsh.d"
        mode: "0750"
        minimal: true

      # Themed items
      # - src: "{{ colorscheme['wallpaper'] | default(False) }}"
      #   dst: "{{ xdg_config_home }}/wallpaper.png"
      # - src: "{{ colorscheme['conkyrc'] | default(False) }}"
      #   dst: "{{ xdg_config_home }}/conky/conkyrc"

  tasks:
    - name: collect facts
      setup:
        gather_subset:
          - '!all'

    - name: configure nixos
      become: yes
      register: nixos
      file:
        follow: true
        state: link
        src: "{{ playbook_dir }}/nixos"
        path: /etc/nixos
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: "0640"
      when: "(become | bool) and (not ci) and (ansible_distribution == 'NixOS')"

    - name: make user symlink dirs
      file:
        follow: true
        state: directory
        path: "{{ item.dst | dirname }}"
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0775') }}"
      when: "not (item.graphical | default(False)) or (item.graphical and graphical)"
      with_items: "{{ symlinks }}"

    - name: make user symlinks
      file:
        follow: true
        state: link
        src: "{{ playbook_dir }}/files/{{ item.src }}"
        path: "{{ item.dst }}"
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0640') }}"
      when: >
        item.src != False
        and (not (item.graphical | default(False)) or (item.graphical and graphical))
        and ((item.minimal | default(False)) or ((item.minimal | default(False)) == minimal))
      with_items: "{{ symlinks }}"

    - name: render user templates
      template:
        src: "{{ playbook_dir }}/templates/{{ item.src }}.j2"
        dest: "{{ item.dst }}"
        owner: "{{ item.owner | default(username) }}"
        group: "{{ item.group | default(username) }}"
        mode: "{{ item.mode | default('0640') }}"
      when: "graphical"
      with_items:
        - src: Xresources
          dst: "{{ home }}/.Xresources"

    - name: clone spacemacs
      git:
        repo: 'https://github.com/syl20bnr/spacemacs'
        dest: "{{ home }}/.emacs.d"
        clone: yes
        update: no

    # TODO and build
    # nix-shell --pure -p libtool -p cmake -p libvterm --run "cmake .. && make"
    - name: clone emacs-libvterm
      git:
        repo: 'https://github.com/akermu/emacs-libvterm.git'
        dest: "{{ home }}/.emacs.d/private"
        clone: yes
        update: no

    - name: handle xrdb changes
      command: xrdb -merge $HOME/.Xresources
      when: "not ci and graphical"

    # rather than diffing the config file, just run some commands...
    - name: configure qutebrowser
      command: qutebrowser "{{ setting }}"
      when: "not ci and graphical"
      with_items:
        - setting: ':set fonts.monospace Hack'
        - setting: ':set fonts.downloads "6pt monospace"'
        - setting: ':set fonts.completion.entry "6pt monospace"'
        - setting: ':set fonts.tabs "8pt monospace"'
        - setting: ':set fonts.statusbar "8pt monospace"'

    # - name: set new background
    #   command: "feh --bg-scale {{ xdg_config_home }}/wallpaper.png"

    - include: os/ubuntu.yml
      when: ansible_distribution == "Ubuntu"
