# https://langston-barrett.github.io/lun/

# TODO: rumdl

# mtime = true
# refs = ["origin/main"]
ignore = ["./files/qutebrowser/config.py"]

# -------------------------------------
# bash

[[linter]]
name = "bash"
cmd = "bash -n --"
files = ["*.bash"]

[[linter]]
name = "shellcheck-bash"
cmd = "shellcheck --color=always --shell=bash --"
files = ["*.bash"]

# -------------------------------------
# gha

[[tool]]
name = "zizmor"
configs = []

# -------------------------------------
# json

[[linter]]
name = "jq"
cmd = "jq null --"
files = ["*.json"]

# -------------------------------------
# make

[[linter]]
name = "make"
cmd = "make -n --"
files = ["**/Makefile", "*.mk"]

# -------------------------------------
# md

[[tool]]
name = "mdlynx"

[[tool]]
name = "typos"
configs = []

# -------------------------------------
# python

[[linter]]
name = "py"
cmd = "./scripts/lint/py.py --"
files = ["*.py"]

[[tool]]
name = "ruff check"
configs = []

[[tool]]
name = "ruff format"
configs = []

[[tool]]
name = "ty"
configs = []

# -------------------------------------
# rust

[[tool]]
name = "cargo clippy"
configs = ["kludge/Cargo.toml"]
cd = "kludge"

[[tool]]
name = "cargo fmt"
configs = ["kludge/Cargo.toml"]
cd = "kludge"

# -------------------------------------
# sh

[[linter]]
name = "shellcheck"
cmd = "shellcheck --color=always --shell=bash --"
files = ["*.sh"]

# -------------------------------------
# toml

[[tool]]
name = "taplo"

# -------------------------------------
# txt

[[tool]]
name = "ttlint"

[[linter]]
name = "xref"
cmd = "./scripts/lint/xref.py  --"
files = ["*"]
granularity = "batch"

# -------------------------------------
# zsh

[[linter]]
name = "shellcheck-zsh"
cmd = "shellcheck --color=always --shell=bash --"
files = ["*.zsh"]

# [[linter]]
# name = "zsh"
# cmd = "zsh -n --"
# files = ["*.zsh"]
