;;-*-coding: utf-8;-*-
(define-abbrev-table 'global-abbrev-table
  '(
    ("todo" "TODO(lb):" nil :count 0)
    ("mb" "mv" nil :count 0)
    ("Souffle" "Soufflé" nil :count 0)
    ("ChrisF" "Chris Fahlbusch" nil :count 0)
    ("EMW" "Eric Woldridge" nil :count 0)
    ("RobW" "Rob Wiltbank" nil :count 0)
    ("NLS" "Nichole Schmanski" nil :count 0)
    ("Garcia" "García" nil :count 0)
    ("Marquez" "Márquez" nil :count 0)
    ("naive" "naïve" nil :count 0)
    ("lcear" "clear" nil :count 0)
    ("polymorpha" "Promotion to Optimal Languages Yielding Modular Operator-driven
Replacements and Programmatic Hooks" nil :count 0)
    ("UWA" "University of Washington" nil :count 0)
    ("UABA" "University of Alabama, Birmingham" nil :count 0)
    ("p-u" "parameterized-utils" nil :count 0)
    ("b/w" "between" nil :count 0)
    ("w/" "with" nil :count 0)
    ("w/r/t" "with respect to" nil :count 0)
    ("Appetit" "Appétit" nil :count 0)
    ("appetit" "appétit" nil :count 0)
   ))
