# https://ianthehenry.com/posts/how-to-configure-tmux/
# https://github.com/tmux-plugins/tmux-sensible/blob/master/sensible.tmux
unbind -a
unbind -a -T root
unbind -a -T copy-mode-vi

set -g status off
set -g mode-keys vi

# emacs keybinds in command prompt
set -g status-keys emacs

# Remove delay after pressing ESC
set -s escape-time 0

# Increase scrollback buffer size from 2000 lines
set -g history-limit 20000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

set -g mouse on

# Colors
# https://stackoverflow.com/questions/41783367
set -g default-terminal "xterm-256color"
set -sa terminal-overrides ",xterm*:Tc"
set -as terminal-features ",xterm*:RGB"

# C-space as prefix
set -g prefix C-Space
bind C-Space send-prefix

bind r source-file ~/.tmux.conf
bind n next-window
bind p previous-window
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind d kill-pane
# bind H swap-pane -L
# bind J swap-pane -D
# bind K swap-pane -U
# bind L swap-pane -R
bind / split-window -h
bind - split-window -v

# tmux windows are like Spacemacs buffers, so bind them under "b"
bind b switch-client -T buffer
bind -T buffer n next-window
bind -T buffer p next-window

# tmux panes are like Spacemacs windows, so bind them under "w"
bind w switch-client -T window
bind -T window h select-pane -L
bind -T window j select-pane -D
bind -T window k select-pane -U
bind -T window l select-pane -R
bind -T window d kill-pane

source ${HOME}/code/dots/files/tmux/copy.tmux

