# see conf.sh
[cmds.cabal]
short = "cb"

[cmds.cabal.flags]
c- = "config-file"
de = "default-user-config"
di = "disable-nix"
en = "enable-nix"
hp = "help"
ht = "http-transport"
ig = "ignore-expiry"
n = "numeric-version"
ve = "version"

[cmds.cabal.subs.bench]
short = "be"

[cmds.cabal.subs.build]
short = "b"

[cmds.cabal.subs.cabal]
short = "ca"

[cmds.cabal.subs.check]
short = "ch"

[cmds.cabal.subs.clean]
short = "cl"

[cmds.cabal.subs.configure]
short = "cu"

[cmds.cabal.subs.exec]
short = "ex"

[cmds.cabal.subs.fetch]
short = "fe"

[cmds.cabal.subs.freeze]
short = "fr"

[cmds.cabal.subs.gen-bounds]
short = "gn"

[cmds.cabal.subs.get]
short = "gt"

[cmds.cabal.subs.haddock]
short = "ha"

[cmds.cabal.subs.help]
short = "hp"

[cmds.cabal.subs.hscolour]
short = "hs"

[cmds.cabal.subs.info]
short = "if"

[cmds.cabal.subs.init]
short = "ii"

[cmds.cabal.subs.install]
short = "is"

[cmds.cabal.subs.list]
short = "l"

[cmds.cabal.subs.outdated]
short = "o"

[cmds.cabal.subs.repl]
short = "rl"

[cmds.cabal.subs.report]
short = "ro"

[cmds.cabal.subs.run]
short = "r"

[cmds.cabal.subs.sdist]
short = "s"

[cmds.cabal.subs.test]
short = "t"

[cmds.cabal.subs.update]
short = "ud"

[cmds.cabal.subs.upload]
short = "ul"

[cmds.cabal.subs.user-config]
short = "us"

[cmds.cabal.subs.v1-bench]
short = "v1e"

[cmds.cabal.subs.v1-build]
short = "v1u"

[cmds.cabal.subs.v1-clean]
short = "v1l"

[cmds.cabal.subs.v1-configure]
short = "v1n"

[cmds.cabal.subs.v1-copy]
short = "v1p"

[cmds.cabal.subs.v1-freeze]
short = "vf"

[cmds.cabal.subs.v1-haddock]
short = "vh"

[cmds.cabal.subs.v1-install]
short = "vi"

[cmds.cabal.subs.v1-reconfigure]
short = "vc"

[cmds.cabal.subs.v1-register]
short = "vg"

[cmds.cabal.subs.v1-repl]
short = "vp"

[cmds.cabal.subs.v1-run]
short = "vu"

[cmds.cabal.subs.v1-test]
short = "vt"

[cmds.cabal.subs.v2-bench]
short = "v2-be"

[cmds.cabal.subs.v2-build]
short = "v2-bu"

[cmds.cabal.subs.v2-clean]
short = "vl"

[cmds.cabal.subs.v2-configure]
short = "vo"

[cmds.cabal.subs.v2-exec]
short = "v2e"

[cmds.cabal.subs.v2-freeze]
short = "v2f"

[cmds.cabal.subs.v2-haddock]
short = "v2h"

[cmds.cabal.subs.v2-install]
short = "v2i"

[cmds.cabal.subs.v2-repl]
short = "v2-re"

[cmds.cabal.subs.v2-run]
short = "v2-ru"

[cmds.cabal.subs.v2-sdist]
short = "v2s"

[cmds.cabal.subs.v2-test]
short = "v2t"

[cmds.cabal.subs.v2-update]
short = "v2u"

[cmds.cargo]
short = "cg"

[cmds.cargo.flags]
col = "color"
con = "config"
e = "explain"
f = "frozen"
h = "help"
li = "list"
lo = "locked"
o = "offline"
q = "quiet"
vb = "verbose"
vs = "version"

[cmds.cargo.subs.add]
short = "a"

[cmds.cargo.subs.bench]
short = "be"

[cmds.cargo.subs.build]
short = "b"

[cmds.cargo.subs.check]
short = "c"

[cmds.cargo.subs.clean]
short = "cl"

[cmds.cargo.subs.doc]
short = "d"

[cmds.cargo.subs.init]
short = "ii"

[cmds.cargo.subs.install]
short = "is"

[cmds.cargo.subs.new]
short = "n"

[cmds.cargo.subs.publish]
short = "p"

[cmds.cargo.subs.remove]
short = "re"

[cmds.cargo.subs.run]
short = "r"

[cmds.cargo.subs.search]
short = "s"

[cmds.cargo.subs.test]
short = "t"

[cmds.cargo.subs.uninstall]
short = "un"

[cmds.cargo.subs.update]
short = "up"

[cmds.docker]
short = "dk"

[cmds.docker.flags]
cg = "config"
ct = "context"
de = "debug"
ho = "host"
l- = "log-level"
tk = "tlskey"
tla = "tlscacert"
tle = "tlscert"
ts = "tls"
tv = "tlsverify"
vn = "version"

[cmds.docker.subs.attach]
short = "a"

[cmds.docker.subs.build]
short = "bd"

[cmds.docker.subs.builder]
short = "be"

[cmds.docker.subs.buildx]
short = "bx"

[cmds.docker.subs.commit]
short = "com"

[cmds.docker.subs.compose]
short = "cop"

[cmds.docker.subs.config]
short = "cg"

[cmds.docker.subs.container]
short = "ca"

[cmds.docker.subs.context]
short = "ct"

[cmds.docker.subs.cp]
short = "cp"

[cmds.docker.subs.create]
short = "cr"

[cmds.docker.subs.daemon]
short = "da"

[cmds.docker.subs.diff]
short = "di"

[cmds.docker.subs.events]
short = "ev"

[cmds.docker.subs.exec]
short = "ee"

[cmds.docker.subs.export]
short = "ep"

[cmds.docker.subs.history]
short = "hi"

[cmds.docker.subs.image]
short = "ie"

[cmds.docker.subs.images]
short = "ims"

[cmds.docker.subs.import]
short = "ip"

[cmds.docker.subs.info]
short = "if"

[cmds.docker.subs.inspect]
short = "is"

[cmds.docker.subs.kill]
short = "k"

[cmds.docker.subs.load]
short = "la"

[cmds.docker.subs.login]
short = "li"

[cmds.docker.subs.logout]
short = "lo"

[cmds.docker.subs.logs]
short = "ls"

[cmds.docker.subs.manifest]
short = "m"

[cmds.docker.subs.network]
short = "ne"

[cmds.docker.subs.node]
short = "no"

[cmds.docker.subs.pause]
short = "pa"

[cmds.docker.subs.plugin]
short = "pl"

[cmds.docker.subs.port]
short = "po"

[cmds.docker.subs.ps]
short = "ps"

[cmds.docker.subs.pull]
short = "pul"

[cmds.docker.subs.push]
short = "pus"

[cmds.docker.subs.rename]
short = "rn"

[cmds.docker.subs.restart]
short = "rs"

[cmds.docker.subs.rm]
short = "rm"

[cmds.docker.subs.rmi]
short = "ri"

[cmds.docker.subs.run]
short = "ru"

[cmds.docker.subs.save]
short = "sa"

[cmds.docker.subs.search]
short = "sea"

[cmds.docker.subs.secret]
short = "sec"

[cmds.docker.subs.service]
short = "ser"

[cmds.docker.subs.stack]
short = "sc"

[cmds.docker.subs.start]
short = "sr"

[cmds.docker.subs.stats]
short = "st"

[cmds.docker.subs.stop]
short = "so"

[cmds.docker.subs.swarm]
short = "sw"

[cmds.docker.subs.system]
short = "sy"

[cmds.docker.subs.tag]
short = "ta"

[cmds.docker.subs.top]
short = "to"

[cmds.docker.subs.trust]
short = "tr"

[cmds.docker.subs.unpause]
short = "un"

[cmds.docker.subs.update]
short = "up"

[cmds.docker.subs.version]
short = "vn"

[cmds.docker.subs.volume]
short = "vo"

[cmds.docker.subs.wait]
short = "w"

[cmds.gh]
short = "gh"

[cmds.gh.flags]
hp = "help"
v = "version"

[cmds.gh.subs.actions]
short = "ac"

[cmds.gh.subs.alias]
short = "al"

[cmds.gh.subs.api]
short = "ap"

[cmds.gh.subs.auth]
short = "au"

[cmds.gh.subs.browse]
short = "b"

[cmds.gh.subs.codespace]
short = "cd"

[cmds.gh.subs.completion]
short = "cm"

[cmds.gh.subs.config]
short = "cn"

[cmds.gh.subs.environment]
short = "en"

[cmds.gh.subs.exit-codes]
short = "ei"

[cmds.gh.subs.extension]
short = "et"

[cmds.gh.subs.formatting]
short = "f"

[cmds.gh.subs.gist]
short = "gi"

[cmds.gh.subs.gpg-key]
short = "gp"

[cmds.gh.subs.help]
short = "hp"

[cmds.gh.subs.issue]
short = "i"

[cmds.gh.subs.label]
short = "l"

[cmds.gh.subs.mintty]
short = "m"

[cmds.gh.subs.pr]
short = "p"

[cmds.gh.subs.reference]
short = "rf"

[cmds.gh.subs.release]
short = "rl"

[cmds.gh.subs.repo]
short = "rp"

[cmds.gh.subs.run]
short = "ru"

[cmds.gh.subs.search]
short = "sa"

[cmds.gh.subs.secret]
short = "sc"

[cmds.gh.subs.ssh-key]
short = "ss"

[cmds.gh.subs.status]
short = "st"

[cmds.gh.subs.workflow]
short = "w"

[cmds.git]
short = "g"

[cmds.git.flags]
pg = "paginate"

[cmds.git.subs.add]
short = "a"

[cmds.git.subs.am]
short = "am"

[cmds.git.subs.annotate]
short = "an"

[cmds.git.subs.apply]
short = "ap"

[cmds.git.subs.archimport]
short = "arm"

[cmds.git.subs.archive]
short = "arv"

[cmds.git.subs.bisect]
short = "bi"

[cmds.git.subs.blame]
short = "bl"

[cmds.git.subs.branch]
short = "br"

[cmds.git.subs.bugreport]
short = "bg"

[cmds.git.subs.bundle]
short = "bn"

[cmds.git.subs.cat-file]
short = "ca"

[cmds.git.subs.check-attr]
short = "cha"

[cmds.git.subs.check-ignore]
short = "chi"

[cmds.git.subs.check-mailmap]
short = "chm"

[cmds.git.subs.check-ref-format]
short = "chr"

[cmds.git.subs.checkout]
short = "co"

[cmds.git.subs.checkout-index]
short = "cho"

[cmds.git.subs.cherry]
short = "cy"

[cmds.git.subs.cherry-pick]
short = "c-"

[cmds.git.subs.citool]
short = "ci"

[cmds.git.subs.clean]
short = "cle"

[cmds.git.subs.clone]
short = "clo"

[cmds.git.subs.column]
short = "col"

[cmds.git.subs.commit]
short = "cm"

[cmds.git.subs.commit-graph]
short = "cg"

[cmds.git.subs.commit-tree]
short = "ct"

[cmds.git.subs.config]
short = "con"

[cmds.git.subs.count-objects]
short = "cou"

[cmds.git.subs.credential]
short = "cl"

[cmds.git.subs.credential-cache]
short = "cc"

[cmds.git.subs.credential-netrc]
short = "cn"

[cmds.git.subs.credential-store]
short = "cs"

[cmds.git.subs.cvsexportcommit]
short = "cve"

[cmds.git.subs.cvsimport]
short = "cvi"

[cmds.git.subs.cvsserver]
short = "cvs"

[cmds.git.subs.describe]
short = "de"

[cmds.git.subs.diff]
short = "dif"

[cmds.git.subs.diff-files]
short = "df"

[cmds.git.subs.diff-index]
short = "di"

[cmds.git.subs.diff-tree]
short = "dt"

[cmds.git.subs.difftool]
short = "dit"

[cmds.git.subs.fast-export]
short = "fae"

[cmds.git.subs.fast-import]
short = "fai"

[cmds.git.subs.fetch]
short = "fh"

[cmds.git.subs.fetch-pack]
short = "f-"

[cmds.git.subs.filter-branch]
short = "fi"

[cmds.git.subs.fmt-merge-msg]
short = "fm"

[cmds.git.subs.for-each-ref]
short = "ff"

[cmds.git.subs.for-each-repo]
short = "fp"

[cmds.git.subs.format-patch]
short = "fom"

[cmds.git.subs.fsck]
short = "fs"

[cmds.git.subs.gc]
short = "gc"

[cmds.git.subs.get-tar-commit-id]
short = "ge"

[cmds.git.subs.gitk]
short = "gk"

[cmds.git.subs.gitweb]
short = "gw"

[cmds.git.subs.grep]
short = "gr"

[cmds.git.subs.gui]
short = "gu"

[cmds.git.subs.hash-object]
short = "ha"

[cmds.git.subs.help]
short = "he"

[cmds.git.subs.hook]
short = "ho"

[cmds.git.subs.http-backend]
short = "ht"

[cmds.git.subs.imap-send]
short = "im"

[cmds.git.subs.index-pack]
short = "id"

[cmds.git.subs.init]
short = "ii"

[cmds.git.subs.instaweb]
short = "is"

[cmds.git.subs.interpret-trailers]
short = "it"

[cmds.git.subs.lfs]
short = "lf"

[cmds.git.subs.log]
short = "l"

[cmds.git.subs.ls-files]
short = "lsf"

[cmds.git.subs.ls-remote]
short = "lsr"

[cmds.git.subs.ls-tree]
short = "lst"

[cmds.git.subs.mailinfo]
short = "mi"

[cmds.git.subs.mailsplit]
short = "ms"

[cmds.git.subs.maintenance]
short = "mn"

[cmds.git.subs.merge]
short = "me"

[cmds.git.subs.merge-base]
short = "meb"

[cmds.git.subs.merge-file]
short = "mef"

[cmds.git.subs.merge-index]
short = "mei"

[cmds.git.subs.merge-one-file]
short = "meo"

[cmds.git.subs.merge-tree]
short = "met"

[cmds.git.subs.mergetool]
short = "mt"

[cmds.git.subs.mktag]
short = "ma"

[cmds.git.subs.mktree]
short = "mr"

[cmds.git.subs.multi-pack-index]
short = "mu"

[cmds.git.subs.mv]
short = "mv"

[cmds.git.subs.name-rev]
short = "na"

[cmds.git.subs.notes]
short = "no"

[cmds.git.subs.p4]
short = "p4"

[cmds.git.subs.pack-objects]
short = "po"

[cmds.git.subs.pack-redundant]
short = "pd"

[cmds.git.subs.pack-refs]
short = "pf"

[cmds.git.subs.patch-id]
short = "pt"

[cmds.git.subs.prune]
short = "pe"

[cmds.git.subs.prune-packed]
short = "p-"

[cmds.git.subs.pull]
short = "pl"

[cmds.git.subs.push]
short = "ps"

[cmds.git.subs.quiltimport]
short = "q"

[cmds.git.subs.range-diff]
short = "ra"

[cmds.git.subs.read-tree]
short = "rea"

[cmds.git.subs.rebase]
short = "rb"

[cmds.git.subs.reflog]
short = "ref"

[cmds.git.subs.remote]
short = "rem"

[cmds.git.subs.repack]
short = "repa"

[cmds.git.subs.replace]
short = "repl"

[cmds.git.subs.request-pull]
short = "req"

[cmds.git.subs.rerere]
short = "rer"

[cmds.git.subs.reset]
short = "re"

[cmds.git.subs.restore]
short = "rt"

[cmds.git.subs.rev-list]
short = "rl"

[cmds.git.subs.rev-parse]
short = "rp"

[cmds.git.subs.revert]
short = "ree"

[cmds.git.subs.rm]
short = "rm"

[cmds.git.subs.send-email]
short = "see"

[cmds.git.subs.send-pack]
short = "sep"

[cmds.git.subs.sh-i18n]
short = "shi"

[cmds.git.subs.sh-setup]
short = "shs"

[cmds.git.subs.shortlog]
short = "shr"

[cmds.git.subs.show]
short = "shw"

[cmds.git.subs.show-branch]
short = "sb"

[cmds.git.subs.show-index]
short = "si"

[cmds.git.subs.show-ref]
short = "sr"

[cmds.git.subs.sparse-checkout]
short = "sp"

[cmds.git.subs.stash]
short = "sta"

[cmds.git.subs.status]
short = "s"

[cmds.git.subs.stripspace]
short = "str"

[cmds.git.subs.submodule]
short = "su"

[cmds.git.subs.svn]
short = "sv"

[cmds.git.subs.switch]
short = "sw"

[cmds.git.subs.symbolic-ref]
short = "sy"

[cmds.git.subs.tag]
short = "t"

[cmds.git.subs.unpack-file]
short = "uf"

[cmds.git.subs.unpack-objects]
short = "uo"

[cmds.git.subs.update-index]
short = "ui"

[cmds.git.subs.update-ref]
short = "ur"

[cmds.git.subs.update-server-info]
short = "us"

[cmds.git.subs.var]
short = "va"

[cmds.git.subs.verify-commit]
short = "vc"

[cmds.git.subs.verify-pack]
short = "vp"

[cmds.git.subs.verify-tag]
short = "vt"

[cmds.git.subs.whatchanged]
short = "wh"

[cmds.git.subs.worktree]
short = "wo"

[cmds.git.subs.write-tree]
short = "wr"

[cmds.glab]
short = "gl"

[cmds.glab.flags]
hp = "help"
ve = "version"

[cmds.glab.subs.alias]
short = "al"

[cmds.glab.subs.api]
short = "ap"

[cmds.glab.subs.auth]
short = "au"

[cmds.glab.subs.check-update]
short = "ch"

[cmds.glab.subs.ci]
short = "ci"

[cmds.glab.subs.completion]
short = "cm"

[cmds.glab.subs.config]
short = "cn"

[cmds.glab.subs.help]
short = "hp"

[cmds.glab.subs.issue]
short = "i"

[cmds.glab.subs.label]
short = "l"

[cmds.glab.subs.mr]
short = "m"

[cmds.glab.subs.release]
short = "rl"

[cmds.glab.subs.repo]
short = "rp"

[cmds.glab.subs.ssh-key]
short = "s"

[cmds.glab.subs.user]
short = "u"

[cmds.glab.subs.variable]
short = "va"

[cmds.mdbook]
short = "mdb"

[cmds.mdbook.flags]
hp = "help"
v = "version"

[cmds.mdbook.subs.build]
short = "b"

[cmds.mdbook.subs.clean]
short = "cl"

[cmds.mdbook.subs.completions]
short = "co"

[cmds.mdbook.subs.help]
short = "hp"

[cmds.mdbook.subs.init]
short = "i"

[cmds.mdbook.subs.serve]
short = "s"

[cmds.mdbook.subs.test]
short = "t"

[cmds.mdbook.subs.watch]
short = "w"

