# git help -a
extra_subs = [
  "add",
  "am",
  "annotate",
  "apply",
  "archimport",
  "archive",
  "bisect",
  "blame",
  "branch",
  "bugreport",
  "bundle",
  "cat-file",
  "check-attr",
  "check-ignore",
  "check-mailmap",
  "checkout",
  "checkout-index",
  "check-ref-format",
  "cherry",
  "cherry-pick",
  "citool",
  "clean",
  "clone",
  "column",
  "commit",
  "commit-graph",
  "commit-tree",
  "config",
  "count-objects",
  "credential",
  "credential-cache",
  "credential-netrc",
  "credential-store",
  "cvsexportcommit",
  "cvsimport",
  "cvsserver",
  "daemon",
  "describe",
  "diff",
  "diff-files",
  "diff-index",
  "difftool",
  "diff-tree",
  "fast-export",
  "fast-import",
  "fetch",
  "fetch-pack",
  "filter-branch",
  "fmt-merge-msg",
  "for-each-ref",
  "for-each-repo",
  "format-patch",
  "fsck",
  "gc",
  "get-tar-commit-id",
  "gitk",
  "gitweb",
  "grep",
  "gui",
  "hash-object",
  "help",
  "hook",
  "http-backend",
  "imap-send",
  "index-pack",
  "init",
  "instaweb",
  "interpret-trailers",
  "lfs",
  "log",
  "ls-files",
  "ls-remote",
  "ls-tree",
  "mailinfo",
  "mailsplit",
  "maintenance",
  "merge",
  "merge-base",
  "merge-file",
  "merge-index",
  "merge-one-file",
  "mergetool",
  "merge-tree",
  "mktag",
  "mktree",
  "multi-pack-index",
  "mv",
  "name-rev",
  "notes",
  "p4",
  "pack-objects",
  "pack-redundant",
  "pack-refs",
  "patch-id",
  "prune",
  "prune-packed",
  "pull",
  "push",
  "quiltimport",
  "range-diff",
  "read-tree",
  "rebase",
  "reflog",
  "remote",
  "repack",
  "replace",
  "request-pull",
  "rerere",
  "reset",
  "restore",
  "revert",
  "rev-list",
  "rev-parse",
  "rm",
  "send-email",
  "send-pack",
  "sh-i18n",
  "shortlog",
  "show",
  "show-branch",
  "show-index",
  "show-ref",
  "sh-setup",
  "sparse-checkout",
  "stash",
  "status",
  "stripspace",
  "submodule",
  "svn",
  "switch",
  "symbolic-ref",
  "tag",
  "unpack-file",
  "unpack-objects",
  "update-index",
  "update-ref",
  "update-server-info",
  "var",
  "verify-commit",
  "verify-pack",
  "verify-tag",
  "whatchanged",
  "worktree",
  "write-tree",
]

flags = {}

subs.add = "a"
subs.checkout = "co"
subs.commit = "cm"
subs.log = "l"
subs.rebase = "rb"
