Vagrant.configure("2") do |config|

  # Use a suitable NixOS base. VM built with nixbox are tested to work with
  # this plugin.
  config.vm.box = "nixos/nixos-18.03-x86_64"

  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 4096
    v.cpus = 2
  end

  # set hostname
  config.vm.hostname = "langstonb-hackthebox"
  # TODO connect to wlp2s0
  config.vm.network "public_network"

  # Setup networking
  config.vm.network "private_network", ip: "172.16.16.16"

  config.vm.synced_folder ".", "/etc/nixos/host"

  # config.vm.provision "shell",
  #                     inline: "ls /etc/nixos && exit 1"

  config.vm.provision :nixos,
    # run: 'always',
    inline: %{
{ config, pkgs, ... }:

{
  imports = [ /etc/nixos/host/hosts/hackthebox.nix ];
}
    }

  config.vm.provision "shell", path: "hackthebox.sh"
end
