{
 "title": "Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "systemd-journal",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"systemd-journal\"}"
    }
   ]
  },
  {
   "title": "CPU?",
   "type": "graph",
   "description": "https://stackoverflow.com/questions/48916798/monitoring-cpu-utilization-using-prometheus",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"big\",mode=\"idle\"}[2m])) * 100)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Free Disk Space /",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{job=\"big\",device=\"/dev/sda1\"} / node_filesystem_size_bytes{job=\"big\",device=\"/dev/sda1\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Read Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total[2m])"
    }
   ]
  }
 ]
}