#!/usr/bin/env zsh
alias ga='git add'
alias gb='git branch'
alias gc='git checkout'
alias gcl='git clone --depth 20'
alias gcm='git commit -m'
alias gd='git diff'
alias gdc='git diff --cached'
alias gdm='git diff master'
alias gf='git fetch'
alias gm='git merge'
alias gp='git checkout master && git pull && git checkout -'
alias gpo='git push origin'
alias gr='git reset'
alias grhm='git reset --hard origin/master'
alias gri='git rebase -i'
alias gs='git status'
