theme = "onedark"

# Consider: P
# Recall: spc-y, spc-p
# TODO: How to map normal mode x to select mode x?
[keys.normal]
"@" = "replay_macro"
"$" = "goto_line_end"
"*" = ["search_selection", "search_next"]
"0" = "goto_line_start"
"V" = "extend_line_below"
"q" = "record_macro"
"C-r" = "redo"
"C-j" = "scroll_down"
"C-k" = "scroll_up"

# Looks like this used to work?
# https://github.com/helix-editor/helix/issues/1909
# [keys.normal.space]
# "space" = "command_pallete"

[keys.select]
"$" = "goto_line_end"
"V" = "extend_line_below"
