$pdf_mode = 1;
$pdf_previewer = "zathura";
$pdf_update_method = 0;

@default_files = ("*.Rtex");
$pdflatex = '([[ ! "%T" =~ \.Rtex$ ]] || R --no-save --no-restore -e "'.
'require(knitr);' .
'knit(\'%B.Rtex\');"' .
') && lualatex -file-line-error %O %B'
;