source_all_sh() {[[ -d $1 ]] && for f in $1/*.sh; do source "$f"; done; unset f;}
source_all() {[[ -d $1 ]] && for f in $1/*.zsh; do source "$f"; done; unset f;}
source_all_sh $HOME/.sh.d
source_all $HOME/.zsh.d
