auto_save.session: true
fonts.default_size: "16px"
bindings.commands:
  normal:
    tL: open https://outline.com/{url}
content.images: true
aliases:
  pocket: "open -t https://getpocket.com/edit?url={url}"
zoom.default: "125%"
