name: CI
on:
  push:

defaults:
  run:
    shell: bash
    working-directory: ./kludge

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Deps
      run: |
        rustup update
        rustup component add clippy
    - run: pip install mypy==v1.18.2
    - uses: astral-sh/ruff-action@57714a7c8a2e59f32539362ba31877a1957dded1 # v2.1.4
      with:
        args: "--version"
    - name: create download script
      run: |
        mkdir -p bin
        cat > bin/download <<'EOF'
        curl \
          --fail \
          --location \
          --proto '=https' \
          --show-error \
          --silent \
          --tlsv1.2 \
          "${@}"
        EOF
        chmod +x bin/*
        printf "%s/bin" "${PWD}" >> "${GITHUB_PATH}"
    - name: install mdlynx
      run: |
        download \
          https://github.com/langston-barrett/mdlynx/releases/download/v0.1.0/mdlynx > \
          bin/mdlynx
        chmod +x bin/*
    - name: install typos
      run: |
        download \
          https://github.com/crate-ci/typos/releases/download/v1.39.2/typos-v1.39.2-x86_64-unknown-linux-musl.tar.gz | \
          tar xzf - ./typos
        mv typos bin
        chmod +x bin/*
    - name: install zizmor
      run: |
        download \
          https://github.com/woodruffw/zizmor/releases/download/v1.16.3/zizmor-x86_64-unknown-linux-gnu.tar.gz | \
          tar xzf - ./zizmor
        mv zizmor bin
        chmod +x bin/*

    - uses: Swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1  # 2.8.1
    - run: cd .. && ./scripts/lint/lint.py
    - run: cargo test --locked --no-run
    - run: cargo test
    - run: cargo build --release
    - run: cargo run --release -- whitespace --check . ../files ../nixos ../scripts
